<a href="https://colab.research.google.com/github/PosgradoMNA/actividades-de-aprendizaje-YvTur/blob/main/Semana3_Modulo5_a00813752_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python 101 for Data Science


## Module 5 - Numpy Arrays and simple APIs

###Numpy


####1-Dimension

**Basic Array Creation**

For this we are going to use a popular open source library called Numpy. 
Numpy is a computational mathematics library. This means we have a lot of functions that behind have mathematical methods


In [1]:
#Example of Numpy
import numpy as np
#We first declarete the array
a=np.array([0,1,2,3,4,5])
#we estimate the size of the array
a.size


6

In [2]:
#we can review the dimensionality
a.ndim

1

In [3]:
#The size of the array in each dimension
a.shape

(6,)

**Indexing and slicing methods**


In [4]:
c=np.array([20,10,2,3,4,5])
c

array([20, 10,  2,  3,  4,  5])

In [5]:
#The arrays work as the same in other languages or like the list
#Lets replace the value of the first position 
c[0]=100
c

array([100,  10,   2,   3,   4,   5])

In [6]:
#We can add value to a range of indexes
c[3:5]=300,400,
c

array([100,  10,   2, 300, 400,   5])

**Basic Operations**

In difference with the traditional operations made with python. The numpy library is optimized and requieres less memory. 

In [7]:
from numpy.lib.function_base import vectorize
#How to sum vectors using numpy
u=np.array([1,0])
v=np.array([0,1])
z=u+v
z
#This can work also for rest

array([1, 1])

In [8]:
#We can also do multiplitation with a sacalar
y=np.array([1,2])
z=2*y
z

array([2, 4])

In [9]:
#Product of tw numpy arrays
u=np.array([1,2])
v=np.array([3,2])
z=u*v
z

array([3, 4])

In [10]:
#Cambiare a español porque ocupo anotar estos puntos en mi idioma natal
#Producto Punto
#Era la transpuesta de un vector por el otro 

u=np.array([1,2])
v=np.array([3,1])
r=np.dot(u,v)
r

5

In [11]:
#adding constant to a numpy array
u=np.array([1,2,3,4,-1])
z=u+1
z

array([2, 3, 4, 5, 0])

In [12]:
#Exercise
np.dot(np.array([1,-1]),np.array([1,1]))

0

####2-Dimension


In [27]:
a=[[11,12,13],[21,22,23],[31,32,33]]
A=np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [28]:
#this will provide the dimenssions of the array
A.ndim

2

In [29]:
#this will provide the shape or also interpreted as numbers of columns and rows
A.shape

(3, 3)

In [31]:
#Using this function we can see the total number of elements the matriz has
A.size

9

In [34]:
#Multiplication of matrix to matrix
u=[[1,2],[2,2]]
v=[[1,3],[1,3]]
U=np.array(u)
V=np.array(v)
x=U*V
x

array([[1, 6],
       [2, 6]])

In [38]:
#Multiplication of Scaler to matrix
V=np.array(v)
z=2*V;
z

array([[2, 6],
       [2, 6]])

In [39]:
#Exercise
A = np.array([[1,2],[3,4],[5,6],[7,8]])

B = np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)


ValueError: ignored

In [40]:
a=np.array([0,1,0,1,0])

b=np.array([1,0,1,0,1])

a*b

array([0, 0, 0, 0, 0])

In [41]:
a=np.array([0,1])

b=np.array([1,0])

np.dot(a,b)


0

In [42]:
a=np.array([1,1,1,1,1])

a+10

array([11, 11, 11, 11, 11])

####API

**Application programming Interface**

As we call a library, we are using its interface for calling others forms of code

**REST APIs**

**Re**presentation **S**tate **T**ransition

It is the one where we use the internet to send and receive information. 


In [43]:
A='1234567'
A[1::2]

'246'

In [44]:
Name="Michael Jackson"
Name.find('el')

5

In [46]:
d=("A","B","C" )
d[-1]


'C'

In [47]:
A=((11,12),[21,22])
A[0][1]

12

In [48]:
'1,2,3,4'.split(',')

['1', '2', '3', '4']

In [49]:
'A'


'A'

In [53]:
V={'A','B','C' }
V.add('C')
V

{'A', 'B', 'C'}

In [55]:
A=['1','2','3']

for a in A:

  print(2*a)

11
22
33
